name: page

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLISH_DIR: .
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
         (echo "<template>";
         for f in svg/* ; do
           awk -F\" '{ print "'$(basename ${f%.svg})' "$6}' $f
         done
         echo "</template>") >> index.html
         for f in svg/* ; do
           echo "$f" $(basename "${f%%.*}.svg")
           mv "$f" $(basename "${f%%.*}.svg")
         done
         tar cjf picon.tar.bz2 *.svg
         ls -al $PUBLISH_DIR
    - uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
