name: page

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
#    env:
#      PUBLISH_DIR: .
    steps:
    - uses: actions/checkout@v1
    - name: Build
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
         (echo "<template>";
         for f in svg/*.svg ; do
           name=$(basename "$f")
           awk -v name="${name%.svg} " -F\" '{ print name $6}' $f
         done
         echo "</template>") >> index.html
         for f in svg/* ; do
           echo "$f" $(basename "${f%%.*}.svg")
           mv "$f" $(basename "${f%%.*}.svg")
         done
         tar cjf picon.tar.bz2 *.svg
         git config user.name  "${GITHUB_ACTOR}"
         git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
         git remote add origin_token "https://x-access-token:${PERSONAL_TOKEN}@github.com/$GITHUB_REPOSITORY.git"
         git checkout -b gh-pages
         git commit -am "CI: $(date -u) ${GITHUB_SHA}"
         git push origin_token --force
#    - uses: peaceiris/actions-gh-pages@v2.5.0
#        PUBLISH_BRANCH: gh-pages
