#!/usr/bin/awk /[S]TART/,0
name: page

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
         ### START ###
         # BPI_ALL=$(for f in svg/* ; do grep -Po 'M[^"]+' $f | wc -c ; done |  awk '{ total += $1 } END { printf "%i %i",total/NR,NR }')
         (echo '<!doctype HTML>
         <script src="script.js"></script><link rel=stylesheet href=style.css>
         <svg id=logo xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M13,4 13,0 14,0 15,2 15,0 16,0 16,4 15,4 15,4 14,2 14,4 M9,4 9,0 12,0 12,4 M6,4 6,0 8,0 8,1 7,1 7,3 8,3 8,4 M0,4 0,0 3,0 3,2 1,3 1,4 M1,1 1,2 2,2 2,1 M10,1 10,3 11,3 11,1 M6,16 6.25,15 6,8 7.25,7 7.25,5 8.75,5 8.75,7 10,8 9.75,15 10,16 M9,9.5 9,9 7,9 7,9.5 M9,12 9,10 7,10 7,12 7.5,13 8.5,13 M4,4 4,0 5,0 5,4"></path></svg>'
         jq -n --arg text "$(<README.md)" '{"text":$text,"mode":"gfm","context":"yne/picon"}' |
           curl -svd @- https://api.github.com/markdown -HContent-Type:application/json
         echo '
         <form onsubmit=filter(this)><div class=flex><input type=search placeholder="Search Criteria" onchange=filter(this.form)>
         <select name=--view onchange=this.form.style.setProperty(this.name,this.value)><option>tile<option>pico<option>grouped<option>detail</select>
         <label for=editMode><input type=checkbox id=editMode onchange=this.form.dataset[this.id]=this.checked>Edit Mode</label>
         <button class="fab edit" onclick=makeFont()>Build Font</button></div>'
         for f in svg/*.svg ; do
           name=$(basename "${f/.*}")
           awk -v name="${name%.svg}" -F\" '{print"<svg onclick=clip(this) id=\""name"\" viewBox=\"0 0 8 8\"><path d=\""$6"\"></path></svg>"}' "$f"
           #echo mv "$f" "$name"
         done
         echo '</form>')>index.html
         [ -z $GITHUB_ACTOR ] && exit
         mv .github/pages/* .
         for f in svg/* ; do
           echo "$f" $(basename "${f%%.*}.svg")
           mv "$f" $(basename "${f%%.*}.svg")
         done
         tar cjf picon.tar.bz2 *.svg
         git config user.name  "${GITHUB_ACTOR}"
         git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
         git remote add origin_token "https://x-access-token:${PERSONAL_TOKEN}@github.com/$GITHUB_REPOSITORY.git"
         git checkout -b gh-pages
         git add .
         git commit -m "$(date -u) ${GITHUB_SHA}"
         git push origin_token --force
