#!/usr/bin/awk /[S]TART/,0
name: page

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
         ### START ###
         [ -f /tmp/README ] || jq -n --arg text "$(<README.md)" '{"text":$text,"mode":"gfm","context":"'$GITHUB_REPOSITORY'"}' |
           curl -d @- https://api.github.com/markdown -HContent-Type:application/json |
           sed -r 's/<h(.)>(\w+)/<h\1 id=\2>\2/' |
           sed -r 's@.github/pages/@@g' > /tmp/README
         for f in svg/*.svg ; do
           name=$(basename "${f/.*}")
           echo "<option>$name" > /tmp/DATALIST
           echo "<li id='$name' onclick=toggle(this,event)><img src='data:image/svg+xml,include($f)'/><code onclick=clip(this,event)>$name</code></li>" > /tmp/ICONLIST
         done
         node .github/pages/script.js svg/*.svg > picon.otf
         apt install woff2 && woff2_compress picon.otf
         (cd svg ; tar cjf ../picon.tar.bz2 *.svg)
         (cd svg ; zip -9  ../picon.zip     *.svg)
         size(){ du -sh index.html | awk '{print $1"B"}';}
         m4 -DTOTAL=$(ls svg/*|wc -l) -DOTF=$(size *.otf) -DWOFF2=$(size *.woff2) -DBZ2=$(size *.bz2) -DZIP=$(size *.zip) < .github/pages/template.html > index.html
         [ -z $GITHUB_ACTOR ] && exit
         mv .github/pages/* .
         git config user.name  "${GITHUB_ACTOR}"
         git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
         git remote add origin_token "https://x-access-token:${PERSONAL_TOKEN}@github.com/$GITHUB_REPOSITORY.git"
         git checkout -b gh-pages
         git add .
         git commit -m "$(date -u) ${GITHUB_SHA}"
         git push origin_token --force
