#!/usr/bin/awk /[S]TART/,0
name: page

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
         ### START ###
         [ -f /tmp/README ] || jq -n --arg text "$(<README.md)" '{"text":$text,"mode":"gfm","context":"'$GITHUB_REPOSITORY'"}' |
           curl -sd @- https://api.github.com/markdown -HContent-Type:application/json |
           sed -r 's/<h(.)>(\w+)/<h\1 id=\2>\2/' |
           sed -r 's@.github/pages/@@g' > /tmp/README
         rm -f /tmp/DATALIST /tmp/ICONLIST
         for f in svg/*.svg ; do
           name=$(basename "${f/.*}")
           echo "<option>$name" >> /tmp/DATALIST
           echo "<li id='$name' onclick=toggle(this,event)><img src='data:image/svg+xml,include($f)'/><code onclick=clip(this,event)>$name</code></li>" >> /tmp/ICONLIST
         done
         [ -f .github/pages/opentype.js ] || wget -qO .github/pages/opentype.js https://cdn.jsdelivr.net/npm/opentype.js
         node .github/pages/script.js METADATA.pb svg/*.svg > Picon-Regular.otf
         command -v woff2_compress || sudo apt install -y woff2
         woff2_compress *.otf
         command -v fontforge      || sudo apt install -y fontforge
         fontforge -lang=ff -c 'Open($1);Generate($2)' Picon-Regular.otf /tmp/Picon-Regular.ttf
         command -v ttfautohint    || sudo apt install -y ttfautohint
         ttfautohint /tmp/Picon-Regular.ttf Picon-Regular.ttf
         (cd svg ; tar cjf ../Picon-Regular.tar.bz2 *.svg)
         size(){ du -sh $1 | awk '{print $1"B"}';}
         m4 -DSVG_COUNT=$(ls svg/*|wc -l) -DWOFF2_SIZE=$(size *.woff2) -DBZ2_SIZE=$(size *.bz2) < .github/pages/template.html > index.html
         [ -z $GITHUB_ACTOR ] && exit
         mv .github/pages/* .
         git config user.name  "${GITHUB_ACTOR}"
         git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
         git remote add origin_token "https://x-access-token:${PERSONAL_TOKEN}@github.com/$GITHUB_REPOSITORY.git"
         git checkout -b gh-pages
         git add .
         git commit -m "$(date -u) ${GITHUB_SHA}"
         git push origin_token --force
