#!/usr/bin/awk /[S]TART/,0
name: page

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
         ### START ###
         jq -n --arg text "$(<README.md)" '{"text":$text,"mode":"gfm","context":"'$GITHUB_REPOSITORY'"}' |
           curl -sd @- https://api.github.com/markdown -HContent-Type:application/json |
           sed -r 's/<h(.)>(\w+)/<h\1 id=\2>\2/' |
           sed -r 's@.github/pages/@@g' > /tmp/README
         (for f in svg/*.svg ; do echo '<option value="'$(basename "${f/.*}")'">'; done)>/tmp/DATALIST
         (for f in svg/*.svg ; do echo "--><a onclick=clip(this,event) tabindex=1 id='"$(basename "${f/.*}")"'><input type=checkbox onclick=toggle(this,event)>$(<$f)</a><!--" ; done)>/tmp/ICONLIST
         m4 < .github/pages/template.html > index.html
         [ -z $GITHUB_ACTOR ] && exit
         mv .github/pages/* .
         for f in svg/* ; do
           echo "$f" $(basename "${f%%.*}.svg")
           mv "$f" $(basename "${f%%.*}.svg")
         done
         tar cjf picon.tar.bz2 *.svg
         zip -9  picon.zip     *.svg
         git config user.name  "${GITHUB_ACTOR}"
         git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
         git remote add origin_token "https://x-access-token:${PERSONAL_TOKEN}@github.com/$GITHUB_REPOSITORY.git"
         git checkout -b gh-pages
         git add .
         git commit -m "$(date -u) ${GITHUB_SHA}"
         git push origin_token --force
