#!/usr/bin/awk /[S]TART/,0
name: page

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      pages: .github/pages
    steps:
    - uses: actions/checkout@v2
    - name: Prerequist
      working-directory: ${{env.pages}}
      run: |
        sudo apt install -y woff2 fontforge ttfautohint jq
        wget https://cdn.jsdelivr.net/npm/opentype.js
    - name: Build
      run: |
        for f in $(find -name '*.m4'); do
          m4 -DHOST=https://github.com/ -DNAME=${GITHUB_REPOSITORY#*/} -DTYPE=$(basename $(dirname $f)) -DTAG=$(date +v%y.%m.%d) -DOWNER=${GITHUB_ACTOR} -DSHA=${GITHUB_SHA} -DSVG_COUNT=$(ls */*.svg|wc -l) <${f} >${f%.*}
        done
        for type in */ ; do
          TYPE=${type///}
          OUT=$(jq -r .postScriptName < ${TYPE}/manifest.json)
          node .list.js package.json ${TYPE}/manifest.json *.svg > ${TYPE}.json
          node build.js < ${TYPE}.json > $OUT.otf
          fontforge -lang=ff -c 'Open($1);Generate($2)' $OUT.otf $OUT.nohint.ttf
          ttfautohint $OUT.nohint.ttf $OUT.ttf
          convert -density 8192 -resize 512x512 -background transparent apple*.svg ../apple.png
        done
        woff2_compress *.otf
    - name: PageRedact
      run: |
        ### START ###
        size(){ du -sh $1 | awk '{print $1"B"}';}
        [ -f /tmp/README ] || jq -n --arg text "$(<README.md)" '{"text":$text,"mode":"gfm","context":"'$GITHUB_REPOSITORY'"}' |
          curl -sd @- https://api.github.com/markdown > /tmp/README
        TAG=$(date +v%y.%m.%d)
        m4 -DREPO=https://github.com/$GITHUB_REPOSITORY -DTAG=$TAG -DWOFF2_SIZE=$(size *.woff2) -DBZ2_SIZE=$(size *.bz2) < .github/pages/index.m4 > index.html
        convert -background none  -density 5000 -resize 192x192 - logo-192.png << favicon.svg
        convert -background none  -density 5000 -resize 512x512 - logo-512.png << favicon.svg
        convert -background white -density 5000 -resize 180x180 - apple-touch-icon.png << favicon.svg
        convert -background none  -density 5000 -resize 48x48 - favicon.ico << favicon.svg
        # diff showcase
        mkdir diff
    - name: GitHubPage
      run: |
        [ -z "$GITHUB_ACTOR" ] && exit
        git config user.name  "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git remote add origin_token "https://x-access-token:${PERSONAL_TOKEN}@github.com/$GITHUB_REPOSITORY.git"
        git checkout -b gh-pages
        git add .
        git commit -m "$(date -u) ${GITHUB_SHA}"
        git push origin_token --force
    - name: GitHubRelease
      run: |
        message=$(git log -1 --pretty=format:"%s")
        [[ "$message" == "[WIP]"* ]] && exit;
        page=$(curl -v -u:${PERSONAL_TOKEN} -H "Content-Type:application/json" -d '{"tag_name": "'$TAG'"}' https://api.github.com/repos/${GITHUB_REPOSITORY}/releases)
        echo page is "$page"
        upload_url=$(echo "$page" | jq -r .upload_url)
        echo upload on $upload_url
        for f in METADATA.pb Picon-*; do
          curl -u:${PERSONAL_TOKEN} -H "Content-Type: $(file -b --mime-type $f)" --data-binary @$f ${upload_url/{*}?name=$f | jq .browser_download_url
        done
        curl -HAccept:application/vnd.github.mercy-preview+json https://api.github.com/repos/yne/picon |
        jq '{name,version:"'$TAG'",description,homepage,author:.owner.login,license:.license.key,repository:{type:"git",url:.git_url},publishConfig:{registry:"https://npm.pkg.github.com"},keywords:.topics}' > package.json
    - name: NpmPackage
      uses: actions/setup-node@v1
      with: registry-url: 'https://registry.npmjs.org'
    - run: npm publish --access public
      env: NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: GitHubPackage
      uses: actions/setup-node@v1
      with: registry-url: 'https://npm.pkg.github.com'
    - run: npm publish
      env: NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
